const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_REQUEST_COMPLETE = 'LOGIN_REQUEST_COMPLETE';
const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_REQUEST_COMPLETE = 'REGISTER_REQUEST_COMPLETE';
const REGISTER_REQUEST_FAILED = 'REGISTER_REQUEST_FAILED';

const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';
const GET_CURRENT_USER_COMPLETE = 'GET_CURRENT_USER_COMPLETE';

const ADDITION_COMPLETE = 'ADDITION_COMPLETE'

export {
    LOGIN_REQUEST,
    LOGIN_REQUEST_COMPLETE,
    LOGIN_REQUEST_FAILED,

    REGISTER_REQUEST,
    REGISTER_REQUEST_COMPLETE,
    REGISTER_REQUEST_FAILED,

    GET_CURRENT_USER_REQUEST,
    GET_CURRENT_USER_COMPLETE,
    GET_CURRENT_USER_FAILED,

    ADDITION_COMPLETE
};
